import { Geist, Geist_Mono } from "next/font/google";
import { DM_Serif_Display } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import "leaflet/dist/leaflet.css"
import { ThemeProvider } from "@/components/themeProvider"

const dmSerifDisplay = DM_Serif_Display ({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-heading",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Edurater",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
        lang="en" 
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${dmSerifDisplay.variable}`}
      >
      <body className="antialiased">
         <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <NavBar />
        <div className="pt-20">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}